apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-jiteshyadav
  namespace: kubernetes-cluster-jiteshyadav
  labels:
    app: app-jiteshyadav
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-jiteshyadav
  template:
    metadata:
      labels:
        app: app-jiteshyadav
    spec:
      containers:
      - name: app-jiteshyadav-pod
        image: imageName
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: test-config-vars
        - secretRef:
            name: test-config-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: app-jiteshyadav-service
  namespace: kubernetes-cluster-jiteshyadav
  labels:
    kind: service
spec:
  type: LoadBalancer
  selector:
    app: app-jiteshyadav
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
